import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const colleges = [
  { name: "Indian Institute of Technology Bombay", city: "Mumbai", state: "Maharashtra", type: "Government", fees: 250000, rating: 4.8, totalRatings: 2341, established: 1958, nirf: 3, naac: "A++", description: "IIT Bombay is India's premier engineering institution, renowned for cutting-edge research, Nobel laureate faculty, and placement packages that set industry benchmarks year after year.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/IIT_Bombay_-_Lecture_Hall_Complex.jpg/1280px-IIT_Bombay_-_Lecture_Hall_Complex.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 250000, seats: 120 }, { name: "B.Tech Electrical Engineering", duration: 4, fees: 250000, seats: 80 }, { name: "M.Tech AI & Data Science", duration: 2, fees: 150000, seats: 40 }], placement: { avgPackage: 2100, highestPackage: 25000, placementRate: 95, topRecruiters: "Google,Microsoft,Goldman Sachs,McKinsey,Amazon" } },
  { name: "Indian Institute of Technology Delhi", city: "New Delhi", state: "Delhi", type: "Government", fees: 230000, rating: 4.7, totalRatings: 1987, established: 1961, nirf: 2, naac: "A++", description: "IIT Delhi consistently ranks among India's top 2 institutions. Its location in the capital gives students unmatched access to government, policy, and corporate ecosystems.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/IIT_Delhi_Main_Building.jpg/1280px-IIT_Delhi_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 230000, seats: 100 }, { name: "B.Tech Mechanical Engineering", duration: 4, fees: 230000, seats: 90 }], placement: { avgPackage: 1950, highestPackage: 22000, placementRate: 94, topRecruiters: "Samsung,Adobe,Flipkart,Deloitte,Intel" } },
  { name: "Indian Institute of Technology Madras", city: "Chennai", state: "Tamil Nadu", type: "Government", fees: 240000, rating: 4.9, totalRatings: 2100, established: 1959, nirf: 1, naac: "A++", description: "India's #1 ranked institute by NIRF for 8 consecutive years. IIT Madras is a global research powerhouse with strong startup culture and deep industry connections.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/IIT_Madras_Research_Park.jpg/1280px-IIT_Madras_Research_Park.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 240000, seats: 110 }, { name: "B.Tech Chemical Engineering", duration: 4, fees: 240000, seats: 70 }], placement: { avgPackage: 2200, highestPackage: 28000, placementRate: 96, topRecruiters: "Google,Apple,Goldman Sachs,Uber,Qualcomm" } },
  { name: "Indian Institute of Technology Kanpur", city: "Kanpur", state: "Uttar Pradesh", type: "Government", fees: 220000, rating: 4.7, totalRatings: 1654, established: 1959, nirf: 4, naac: "A++", description: "IIT Kanpur is known for academic rigor and pioneering undergraduate research. It was the first Indian institution to offer Computer Science education.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/IIT_Kanpur_-_Lecture_Hall_Complex.jpg/1280px-IIT_Kanpur_-_Lecture_Hall_Complex.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 220000, seats: 90 }, { name: "B.Tech Aerospace", duration: 4, fees: 220000, seats: 40 }], placement: { avgPackage: 2000, highestPackage: 24000, placementRate: 93, topRecruiters: "Microsoft,Amazon,D.E.Shaw,Tower Research,Google" } },
  { name: "Indian Institute of Technology Kharagpur", city: "Kharagpur", state: "West Bengal", type: "Government", fees: 210000, rating: 4.6, totalRatings: 1876, established: 1951, nirf: 5, naac: "A++", description: "India's oldest and largest IIT with a 2100-acre campus. IIT Kharagpur has the most diverse program offering of any IIT, spanning engineering, law, management, and medicine.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/IIT_Kharagpur_Technology_Students_Gymkhana.jpg/1280px-IIT_Kharagpur_Technology_Students_Gymkhana.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 210000, seats: 130 }, { name: "B.Tech Mining Engineering", duration: 4, fees: 210000, seats: 45 }], placement: { avgPackage: 1800, highestPackage: 20000, placementRate: 91, topRecruiters: "Tata,Infosys,Samsung,Goldman Sachs,Wipro" } },
  { name: "BITS Pilani", city: "Pilani", state: "Rajasthan", type: "Deemed", fees: 520000, rating: 4.6, totalRatings: 3102, established: 1964, nirf: 25, naac: "A", description: "BITS Pilani's unique dual-degree and Practice School programs produce industry-ready graduates. Its alumni include founders of major Indian unicorns.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/BITS_Pilani_Main_Gate.jpg/1280px-BITS_Pilani_Main_Gate.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 520000, seats: 140 }, { name: "B.E. Electronics", duration: 4, fees: 520000, seats: 100 }], placement: { avgPackage: 1650, highestPackage: 18000, placementRate: 92, topRecruiters: "Qualcomm,Texas Instruments,Goldman Sachs,Google,Oracle" } },
  { name: "National Institute of Technology Trichy", city: "Tiruchirappalli", state: "Tamil Nadu", type: "Government", fees: 180000, rating: 4.4, totalRatings: 1543, established: 1964, nirf: 9, naac: "A++", description: "NIT Trichy is the crown jewel of NITs, renowned for outstanding placement records in core and IT sectors, and a competitive academic environment.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/NIT_Tiruchirappalli_Main_Gate.jpg/1280px-NIT_Tiruchirappalli_Main_Gate.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 180000, seats: 90 }, { name: "B.Tech Civil Engineering", duration: 4, fees: 180000, seats: 120 }], placement: { avgPackage: 1200, highestPackage: 14000, placementRate: 90, topRecruiters: "TCS,Infosys,Wipro,L&T,Amazon" } },
  { name: "Vellore Institute of Technology", city: "Vellore", state: "Tamil Nadu", type: "Deemed", fees: 420000, rating: 4.2, totalRatings: 4521, established: 1984, nirf: 11, naac: "A++", description: "VIT is India's most internationally connected private university with 900+ MoUs with global universities. Known for its research output and modern infrastructure.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/VIT_University_Vellore_Main_Building.jpg/1280px-VIT_University_Vellore_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 420000, seats: 500 }, { name: "B.Tech Biomedical Engineering", duration: 4, fees: 380000, seats: 60 }], placement: { avgPackage: 850, highestPackage: 12000, placementRate: 85, topRecruiters: "Cognizant,Capgemini,HCL,Accenture,Zoho" } },
  { name: "Delhi Technological University", city: "New Delhi", state: "Delhi", type: "Government", fees: 160000, rating: 4.1, totalRatings: 2876, established: 1941, nirf: 36, naac: "A", description: "Delhi's flagship engineering university. DTU's proximity to the capital's startup ecosystem makes it a hub for entrepreneurship and technology innovation.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/DTU_Main_Building.jpg/1280px-DTU_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 160000, seats: 180 }, { name: "B.Tech Software Engineering", duration: 4, fees: 160000, seats: 90 }], placement: { avgPackage: 1050, highestPackage: 16000, placementRate: 88, topRecruiters: "Microsoft,Amazon,Paytm,Zomato,PhonePe" } },
  { name: "Manipal Institute of Technology", city: "Manipal", state: "Karnataka", type: "Private", fees: 480000, rating: 4.0, totalRatings: 3210, established: 1957, nirf: 51, naac: "A++", description: "MIT Manipal's stunning coastal campus and global alumni network spanning 6 continents make it India's most cosmopolitan private engineering college.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Manipal_Institute_of_Technology_Building.jpg/1280px-Manipal_Institute_of_Technology_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 480000, seats: 300 }, { name: "B.Tech Information Technology", duration: 4, fees: 480000, seats: 120 }], placement: { avgPackage: 780, highestPackage: 10000, placementRate: 82, topRecruiters: "Infosys,TCS,Wipro,IBM,Accenture" } },
  { name: "SRM Institute of Science and Technology", city: "Chennai", state: "Tamil Nadu", type: "Private", fees: 350000, rating: 3.8, totalRatings: 5102, established: 1985, nirf: 30, naac: "A++", description: "One of India's largest universities by enrollment with 52,000+ students, SRM is known for its massive research output and international collaborations.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/SRM_Institute_of_Science_and_Technology.jpg/1280px-SRM_Institute_of_Science_and_Technology.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 350000, seats: 800 }, { name: "B.Tech Mechanical Engineering", duration: 4, fees: 300000, seats: 200 }], placement: { avgPackage: 620, highestPackage: 9000, placementRate: 78, topRecruiters: "Cognizant,HCL,Tech Mahindra,Capgemini,Zoho" } },
  { name: "Anna University", city: "Chennai", state: "Tamil Nadu", type: "Government", fees: 95000, rating: 4.0, totalRatings: 3400, established: 1978, nirf: 14, naac: "A++", description: "Anna University is Tamil Nadu's apex technical university affiliating 500+ engineering colleges. Its CEG campus has produced some of India's finest engineers.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Anna_University_CEG_Campus.jpg/1280px-Anna_University_CEG_Campus.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 95000, seats: 150 }, { name: "B.E. Electronics", duration: 4, fees: 95000, seats: 120 }], placement: { avgPackage: 750, highestPackage: 8500, placementRate: 80, topRecruiters: "TCS,Infosys,Wipro,CTS,HCL" } },
  { name: "Jadavpur University", city: "Kolkata", state: "West Bengal", type: "Government", fees: 45000, rating: 4.3, totalRatings: 1870, established: 1955, nirf: 12, naac: "A", description: "Jadavpur University is West Bengal's premier technical institution, known for producing exceptional engineers and researchers on an incredibly affordable budget.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Jadavpur_University_main_building.jpg/1280px-Jadavpur_University_main_building.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 45000, seats: 60 }, { name: "B.E. Electrical Engineering", duration: 4, fees: 45000, seats: 80 }], placement: { avgPackage: 900, highestPackage: 11000, placementRate: 87, topRecruiters: "TCS,Wipro,IBM,Amazon,Mindtree" } },
  { name: "PSG College of Technology", city: "Coimbatore", state: "Tamil Nadu", type: "Private", fees: 180000, rating: 4.2, totalRatings: 1230, established: 1951, nirf: 45, naac: "A++", description: "PSG Tech is Coimbatore's most respected engineering college with strong industry ties to the city's manufacturing and IT sector.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/PSG_College_of_Technology.jpg/1280px-PSG_College_of_Technology.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 180000, seats: 120 }, { name: "B.E. Mechanical Engineering", duration: 4, fees: 180000, seats: 90 }], placement: { avgPackage: 680, highestPackage: 7500, placementRate: 83, topRecruiters: "TCS,Infosys,L&T,Bosch,Zoho" } },
  { name: "Amrita Vishwa Vidyapeetham", city: "Coimbatore", state: "Tamil Nadu", type: "Deemed", fees: 310000, rating: 4.1, totalRatings: 2100, established: 1994, nirf: 7, naac: "A++", description: "Amrita is India's fastest-rising university in global rankings, excelling in research output particularly in cybersecurity and healthcare technology.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Amrita_Vishwa_Vidyapeetham.jpg/1280px-Amrita_Vishwa_Vidyapeetham.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 310000, seats: 200 }, { name: "B.Tech Cybersecurity", duration: 4, fees: 320000, seats: 60 }], placement: { avgPackage: 720, highestPackage: 9000, placementRate: 82, topRecruiters: "TCS,Infosys,Wipro,Amazon,Cisco" } },
  { name: "National Institute of Technology Surathkal", city: "Mangaluru", state: "Karnataka", type: "Government", fees: 165000, rating: 4.3, totalRatings: 1200, established: 1960, nirf: 18, naac: "A+", description: "NITK Surathkal sits on a breathtaking coastal campus and consistently ranks in India's top 20. Its electronics and CS programs are particularly highly regarded.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/NITK_Surathkal_Main_Building.jpg/1280px-NITK_Surathkal_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 165000, seats: 70 }, { name: "B.Tech Electronics", duration: 4, fees: 165000, seats: 90 }], placement: { avgPackage: 1050, highestPackage: 13000, placementRate: 89, topRecruiters: "Google,Amazon,Qualcomm,Samsung,TCS" } },
  { name: "National Institute of Technology Warangal", city: "Warangal", state: "Telangana", type: "Government", fees: 170000, rating: 4.2, totalRatings: 1450, established: 1959, nirf: 26, naac: "A+", description: "NIT Warangal is Telangana's premier institution with a strong alumni base in Silicon Valley and an aggressive research culture.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/NIT_Warangal_Main_Building.jpg/1280px-NIT_Warangal_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 170000, seats: 80 }, { name: "B.Tech Metallurgical Engineering", duration: 4, fees: 170000, seats: 50 }], placement: { avgPackage: 980, highestPackage: 12000, placementRate: 87, topRecruiters: "Microsoft,Amazon,Google,Wipro,TCS" } },
  { name: "Thapar Institute of Engineering", city: "Patiala", state: "Punjab", type: "Deemed", fees: 430000, rating: 3.9, totalRatings: 1800, established: 1956, nirf: 28, naac: "A", description: "Thapar is Punjab's top engineering institution with a strong focus on research and excellent CSE placements, particularly in product-based companies.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Thapar_University_main_building.jpg/1280px-Thapar_University_main_building.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 430000, seats: 180 }, { name: "B.E. Electronics", duration: 4, fees: 430000, seats: 100 }], placement: { avgPackage: 980, highestPackage: 13000, placementRate: 85, topRecruiters: "Microsoft,Adobe,Amazon,Infosys,Nvidia" } },
  { name: "IIIT Hyderabad", city: "Hyderabad", state: "Telangana", type: "Deemed", fees: 380000, rating: 4.5, totalRatings: 1100, established: 1998, nirf: 32, naac: "A", description: "IIIT-H is a research-intensive institute that punches well above its weight. Its focus on CS and AI produces among India's best software engineers.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/IIIT_Hyderabad_Campus.jpg/1280px-IIIT_Hyderabad_Campus.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 380000, seats: 80 }, { name: "B.Tech Electronics & CS", duration: 4, fees: 380000, seats: 50 }], placement: { avgPackage: 1800, highestPackage: 20000, placementRate: 96, topRecruiters: "Google,Microsoft,Uber,Flipkart,Adobe" } },
  { name: "IIIT Bangalore", city: "Bengaluru", state: "Karnataka", type: "Deemed", fees: 350000, rating: 4.4, totalRatings: 980, established: 1999, nirf: 38, naac: "A", description: "Located in India's tech capital, IIIT Bangalore's industry interface is exceptional. Students get exposure to Bengaluru's startup and product ecosystem from day one.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/IIIT_Bangalore_Main_Building.jpg/1280px-IIIT_Bangalore_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 350000, seats: 70 }, { name: "M.Tech Data Science", duration: 2, fees: 400000, seats: 60 }], placement: { avgPackage: 1600, highestPackage: 18000, placementRate: 94, topRecruiters: "Amazon,Flipkart,Google,Swiggy,Razorpay" } },
  { name: "Pune Institute of Computer Technology", city: "Pune", state: "Maharashtra", type: "Government", fees: 120000, rating: 4.0, totalRatings: 1450, established: 1983, nirf: 89, naac: "A+", description: "PICT Pune is Maharashtra's most respected autonomous engineering college, known for producing exceptional software engineers placed at top MNCs.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/PICT_Pune_Main_Building.jpg/1280px-PICT_Pune_Main_Building.jpg", courses: [{ name: "B.E. Computer Engineering", duration: 4, fees: 120000, seats: 180 }, { name: "B.E. Information Technology", duration: 4, fees: 120000, seats: 120 }], placement: { avgPackage: 820, highestPackage: 9500, placementRate: 88, topRecruiters: "Persistent,Infosys,Wipro,TCS,Capgemini" } },
  { name: "College of Engineering Pune", city: "Pune", state: "Maharashtra", type: "Government", fees: 85000, rating: 4.1, totalRatings: 1700, established: 1854, nirf: 67, naac: "A+", description: "COEP is one of India's oldest engineering colleges. Its autonomous status and strong alumni network make it Pune's most prestigious affordable institution.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/College_of_Engineering_Pune_main_building.jpg/1280px-College_of_Engineering_Pune_main_building.jpg", courses: [{ name: "B.E. Computer Engineering", duration: 4, fees: 85000, seats: 120 }, { name: "B.E. Mechanical Engineering", duration: 4, fees: 85000, seats: 90 }], placement: { avgPackage: 780, highestPackage: 9000, placementRate: 85, topRecruiters: "TCS,Infosys,Capgemini,Mahindra,Tata Motors" } },
  { name: "Symbiosis Institute of Technology", city: "Pune", state: "Maharashtra", type: "Private", fees: 340000, rating: 3.9, totalRatings: 1200, established: 2008, nirf: 101, naac: "A", description: "SIT Pune benefits from the Symbiosis ecosystem with strong industry connections and a modern campus in Lavale that rivals international standards.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Symbiosis_Institute_of_Technology_Pune.jpg/1280px-Symbiosis_Institute_of_Technology_Pune.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 340000, seats: 180 }, { name: "B.Tech AI & ML", duration: 4, fees: 360000, seats: 60 }], placement: { avgPackage: 720, highestPackage: 8500, placementRate: 80, topRecruiters: "TCS,Infosys,Capgemini,Wipro,L&T" } },
  { name: "K.J. Somaiya College of Engineering", city: "Mumbai", state: "Maharashtra", type: "Private", fees: 270000, rating: 3.8, totalRatings: 1100, established: 1983, nirf: 120, naac: "A", description: "KJSCE Mumbai is one of the city's top private engineering colleges with strong industry linkages in Mumbai's financial and tech sector.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/KJ_Somaiya_College_of_Engineering.jpg/1280px-KJ_Somaiya_College_of_Engineering.jpg", courses: [{ name: "B.E. Computer Engineering", duration: 4, fees: 270000, seats: 120 }, { name: "B.E. Electronics", duration: 4, fees: 270000, seats: 90 }], placement: { avgPackage: 650, highestPackage: 7000, placementRate: 78, topRecruiters: "TCS,Infosys,Wipro,Cognizant,Goldman Sachs" } },
  { name: "Veermata Jijabai Technological Institute", city: "Mumbai", state: "Maharashtra", type: "Government", fees: 75000, rating: 4.2, totalRatings: 1560, established: 1887, nirf: 55, naac: "A+", description: "VJTI is Mumbai's oldest and most respected government engineering college. Its heritage building and outstanding alumni make it a truly iconic institution.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/VJTI_Mumbai_Main_Building.jpg/1280px-VJTI_Mumbai_Main_Building.jpg", courses: [{ name: "B.Tech Computer Engineering", duration: 4, fees: 75000, seats: 120 }, { name: "B.Tech Mechanical Engineering", duration: 4, fees: 75000, seats: 90 }], placement: { avgPackage: 870, highestPackage: 10000, placementRate: 86, topRecruiters: "TCS,Infosys,L&T,Wipro,Goldman Sachs" } },
  { name: "National Institute of Technology Calicut", city: "Calicut", state: "Kerala", type: "Government", fees: 155000, rating: 4.2, totalRatings: 1320, established: 1961, nirf: 20, naac: "A+", description: "NIT Calicut is Kerala's top engineering institution, known for rigorous academics and exceptional placement in IT and core sectors.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/NIT_Calicut_Administrative_Block.jpg/1280px-NIT_Calicut_Administrative_Block.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 155000, seats: 80 }, { name: "B.Tech Civil Engineering", duration: 4, fees: 155000, seats: 100 }], placement: { avgPackage: 950, highestPackage: 11500, placementRate: 88, topRecruiters: "TCS,Infosys,Amazon,Wipro,HCL" } },
  { name: "Kerala Technological University", city: "Thiruvananthapuram", state: "Kerala", type: "Government", fees: 70000, rating: 3.9, totalRatings: 890, established: 2014, nirf: 72, naac: "B++", description: "KTU affiliates all government and aided engineering colleges in Kerala. Its model curriculum with strong coding emphasis is transforming Kerala's tech workforce.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Kerala_Technological_University_Logo.jpg/640px-Kerala_Technological_University_Logo.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 70000, seats: 120 }, { name: "B.Tech Civil Engineering", duration: 4, fees: 70000, seats: 90 }], placement: { avgPackage: 580, highestPackage: 6000, placementRate: 72, topRecruiters: "TCS,Infosys,Wipro,UST Global,Mphasis" } },
  { name: "RV College of Engineering", city: "Bengaluru", state: "Karnataka", type: "Private", fees: 195000, rating: 4.1, totalRatings: 1780, established: 1963, nirf: 57, naac: "A++", description: "RVCE Bengaluru is one of Karnataka's top autonomous colleges. Its location in India's Silicon Valley ensures exceptional industry exposure and placement.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/RV_College_of_Engineering_Bangalore.jpg/1280px-RV_College_of_Engineering_Bangalore.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 195000, seats: 180 }, { name: "B.E. Electronics", duration: 4, fees: 195000, seats: 120 }], placement: { avgPackage: 870, highestPackage: 10500, placementRate: 85, topRecruiters: "Amazon,Infosys,Wipro,Accenture,Flipkart" } },
  { name: "PES University", city: "Bengaluru", state: "Karnataka", type: "Private", fees: 420000, rating: 4.0, totalRatings: 2100, established: 1972, nirf: 63, naac: "A", description: "PES University is Bengaluru's fastest-growing private university with an outstanding CS program and placements that rival IITs for top students.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/PES_University_Bangalore.jpg/1280px-PES_University_Bangalore.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 420000, seats: 300 }, { name: "B.Tech Electronics", duration: 4, fees: 380000, seats: 100 }], placement: { avgPackage: 950, highestPackage: 14000, placementRate: 87, topRecruiters: "Amazon,Microsoft,Flipkart,Uber,PayPal" } },
  { name: "BMS College of Engineering", city: "Bengaluru", state: "Karnataka", type: "Private", fees: 175000, rating: 3.9, totalRatings: 1450, established: 1946, nirf: 78, naac: "A+", description: "One of Karnataka's oldest and most respected engineering colleges, BMSCE has produced generations of engineers who now lead global corporations.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/BMS_College_of_Engineering_Bangalore.jpg/1280px-BMS_College_of_Engineering_Bangalore.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 175000, seats: 150 }, { name: "B.E. Mechanical Engineering", duration: 4, fees: 175000, seats: 120 }], placement: { avgPackage: 780, highestPackage: 9000, placementRate: 82, topRecruiters: "Infosys,TCS,Wipro,IBM,Bosch" } },
  { name: "Birla Institute of Technology Mesra", city: "Ranchi", state: "Jharkhand", type: "Deemed", fees: 380000, rating: 3.8, totalRatings: 1200, established: 1955, nirf: 48, naac: "A", description: "BIT Mesra is Jharkhand's premier technical institution with a scenic forested campus and strong placement record in IT and core engineering sectors.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/BIT_Mesra_Main_Building.jpg/1280px-BIT_Mesra_Main_Building.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 380000, seats: 120 }, { name: "B.E. Electronics", duration: 4, fees: 380000, seats: 90 }], placement: { avgPackage: 720, highestPackage: 8000, placementRate: 78, topRecruiters: "TCS,Infosys,Wipro,Capgemini,IBM" } },
  { name: "Dhirubhai Ambani Institute of ICT", city: "Gandhinagar", state: "Gujarat", type: "Deemed", fees: 450000, rating: 4.3, totalRatings: 890, established: 2001, nirf: 31, naac: "A", description: "DA-IICT is India's most focused ICT institution. Its specialized curriculum and Reliance network produce some of India's finest product engineers.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/DA-IICT_Main_Building.jpg/1280px-DA-IICT_Main_Building.jpg", courses: [{ name: "B.Tech ICT", duration: 4, fees: 450000, seats: 200 }, { name: "M.Tech ICT", duration: 2, fees: 300000, seats: 60 }], placement: { avgPackage: 1200, highestPackage: 15000, placementRate: 92, topRecruiters: "Google,Microsoft,Amazon,Jio,Reliance" } },
  { name: "Nirma University", city: "Ahmedabad", state: "Gujarat", type: "Private", fees: 280000, rating: 3.8, totalRatings: 1350, established: 1994, nirf: 59, naac: "A+", description: "Nirma University is Gujarat's most respected private university, offering a strong engineering program with excellent industry connections in Ahmedabad's industrial belt.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Nirma_University_Ahmedabad.jpg/1280px-Nirma_University_Ahmedabad.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 280000, seats: 180 }, { name: "B.Tech Chemical Engineering", duration: 4, fees: 260000, seats: 90 }], placement: { avgPackage: 680, highestPackage: 7500, placementRate: 79, topRecruiters: "TCS,Infosys,Wipro,Reliance,Torrent" } },
  { name: "Charotar University of Science and Technology", city: "Anand", state: "Gujarat", type: "Private", fees: 220000, rating: 3.7, totalRatings: 780, established: 2009, nirf: 80, naac: "A", description: "CHARUSAT is Gujarat's rising star in engineering education, known for innovative pedagogy and strong startup support infrastructure.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/CHARUSAT_University_Gujarat.jpg/1280px-CHARUSAT_University_Gujarat.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 220000, seats: 150 }, { name: "B.Tech Electrical Engineering", duration: 4, fees: 200000, seats: 90 }], placement: { avgPackage: 550, highestPackage: 6000, placementRate: 73, topRecruiters: "TCS,Infosys,Wipro,Cognizant,HCL" } },
  { name: "Kalinga Institute of Industrial Technology", city: "Bhubaneswar", state: "Odisha", type: "Deemed", fees: 280000, rating: 3.9, totalRatings: 2100, established: 1992, nirf: 15, naac: "A++", description: "KIIT has transformed from a tiny polytechnic to a world-class university in 30 years. One of India's fastest-rising institutions with exceptional global exposure.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/KIIT_University_Bhubaneswar.jpg/1280px-KIIT_University_Bhubaneswar.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 280000, seats: 400 }, { name: "B.Tech Biotechnology", duration: 4, fees: 260000, seats: 80 }], placement: { avgPackage: 680, highestPackage: 9000, placementRate: 80, topRecruiters: "TCS,Infosys,Wipro,HCL,Cognizant" } },
  { name: "Lovely Professional University", city: "Phagwara", state: "Punjab", type: "Private", fees: 180000, rating: 3.6, totalRatings: 4200, established: 2005, nirf: 40, naac: "A+", description: "LPU is India's largest single-campus university with 35,000+ students. Known for its vibrant multicultural community and extensive industry tie-ups.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Lovely_Professional_University_Punjab.jpg/1280px-Lovely_Professional_University_Punjab.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 180000, seats: 1000 }, { name: "B.Tech Mechanical Engineering", duration: 4, fees: 160000, seats: 300 }], placement: { avgPackage: 480, highestPackage: 7000, placementRate: 70, topRecruiters: "TCS,Infosys,Wipro,Cognizant,Amazon" } },
  { name: "Chandigarh University", city: "Chandigarh", state: "Punjab", type: "Private", fees: 190000, rating: 3.7, totalRatings: 3600, established: 2012, nirf: 35, naac: "A+", description: "CU is Punjab's fastest-growing university with record-breaking placements year after year. Its aggressive industry partnerships have attracted major global recruiters.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Chandigarh_University_Main_Gate.jpg/1280px-Chandigarh_University_Main_Gate.jpg", courses: [{ name: "B.E. Computer Science", duration: 4, fees: 190000, seats: 600 }, { name: "B.E. Mechanical Engineering", duration: 4, fees: 170000, seats: 200 }], placement: { avgPackage: 520, highestPackage: 7500, placementRate: 75, topRecruiters: "Amazon,TCS,Infosys,Wipro,HCL" } },
  { name: "Shiv Nadar University", city: "Greater Noida", state: "Uttar Pradesh", type: "Private", fees: 550000, rating: 4.2, totalRatings: 780, established: 2011, nirf: 22, naac: "A+", description: "Shiv Nadar University is India's most ambitious new private university. Backed by HCL's founder, its research culture and faculty quality rival IITs.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Shiv_Nadar_University_Campus.jpg/1280px-Shiv_Nadar_University_Campus.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 550000, seats: 120 }, { name: "B.Tech Electronics", duration: 4, fees: 520000, seats: 80 }], placement: { avgPackage: 1100, highestPackage: 14000, placementRate: 89, topRecruiters: "Amazon,Google,HCL,Adobe,Microsoft" } },
  { name: "O.P. Jindal Global University", city: "Sonipat", state: "Haryana", type: "Private", fees: 580000, rating: 4.3, totalRatings: 650, established: 2009, nirf: 16, naac: "A++", description: "OPJ Global is India's premier private law and liberal arts university. Its global faculty and international partnerships make it unique in India's higher education landscape.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/OP_Jindal_Global_University.jpg/1280px-OP_Jindal_Global_University.jpg", courses: [{ name: "B.A. LLB", duration: 5, fees: 580000, seats: 200 }, { name: "B.Com LLB", duration: 5, fees: 560000, seats: 100 }], placement: { avgPackage: 900, highestPackage: 8000, placementRate: 82, topRecruiters: "Cyril Amarchand,AZB,Khaitan,L&L,S&R" } },
  { name: "Ashoka University", city: "Sonipat", state: "Haryana", type: "Private", fees: 620000, rating: 4.4, totalRatings: 420, established: 2014, nirf: 27, naac: "A", description: "Ashoka is India's finest liberal arts university, modeled on top global institutions. Its faculty includes former policymakers, Nobel nominees, and international academics.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Ashoka_University_Haryana.jpg/1280px-Ashoka_University_Haryana.jpg", courses: [{ name: "B.Sc. Computer Science", duration: 3, fees: 620000, seats: 80 }, { name: "B.A. Economics", duration: 3, fees: 580000, seats: 100 }], placement: { avgPackage: 850, highestPackage: 7500, placementRate: 78, topRecruiters: "McKinsey,BCG,Goldman Sachs,Bain,Deloitte" } },
  { name: "Flame University", city: "Pune", state: "Maharashtra", type: "Private", fees: 540000, rating: 4.1, totalRatings: 320, established: 2015, nirf: 48, naac: "A", description: "FLAME is India's premier liberal education university focusing on interdisciplinary thinking. Its alumni go on to top global graduate programs and consulting firms.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/FLAME_University_Pune.jpg/1280px-FLAME_University_Pune.jpg", courses: [{ name: "B.A. Economics", duration: 3, fees: 540000, seats: 100 }, { name: "B.B.A.", duration: 3, fees: 560000, seats: 120 }], placement: { avgPackage: 720, highestPackage: 6000, placementRate: 75, topRecruiters: "Deloitte,KPMG,EY,Bain,Accenture" } },
  { name: "IIM Ahmedabad", city: "Ahmedabad", state: "Gujarat", type: "Government", fees: 2400000, rating: 4.9, totalRatings: 1200, established: 1961, nirf: 1, naac: "A++", description: "India's most prestigious management institution and one of Asia's finest business schools. IIMA graduates run some of the world's largest corporations.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/IIM_Ahmedabad_Louis_Kahn_Plaza.jpg/1280px-IIM_Ahmedabad_Louis_Kahn_Plaza.jpg", courses: [{ name: "MBA (PGP)", duration: 2, fees: 2400000, seats: 400 }, { name: "Executive MBA", duration: 1, fees: 3200000, seats: 100 }], placement: { avgPackage: 3200, highestPackage: 120000, placementRate: 100, topRecruiters: "McKinsey,BCG,Bain,Goldman Sachs,Amazon" } },
  { name: "IIM Bangalore", city: "Bengaluru", state: "Karnataka", type: "Government", fees: 2300000, rating: 4.8, totalRatings: 1100, established: 1973, nirf: 2, naac: "A++", description: "Located in India's startup capital, IIMB is known for entrepreneurship, strategy, and exceptional corporate finance placements. A truly world-class business school.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Indian_Institute_of_Management_Bangalore.jpg/1280px-Indian_Institute_of_Management_Bangalore.jpg", courses: [{ name: "MBA (PGP)", duration: 2, fees: 2300000, seats: 400 }, { name: "PGPEM", duration: 3, fees: 2800000, seats: 80 }], placement: { avgPackage: 3100, highestPackage: 110000, placementRate: 100, topRecruiters: "McKinsey,BCG,Amazon,Flipkart,Goldman Sachs" } },
  { name: "XLRI Jamshedpur", city: "Jamshedpur", state: "Jharkhand", type: "Private", fees: 2100000, rating: 4.6, totalRatings: 780, established: 1949, nirf: 5, naac: "A++", description: "XLRI is India's oldest business school and the gold standard for HR management education. Its BM program rivals IIMs in corporate placement quality.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/XLRI_Jamshedpur_Main_Building.jpg/1280px-XLRI_Jamshedpur_Main_Building.jpg", courses: [{ name: "MBA Business Management", duration: 2, fees: 2100000, seats: 180 }, { name: "MBA Human Resources", duration: 2, fees: 2000000, seats: 120 }], placement: { avgPackage: 2800, highestPackage: 90000, placementRate: 100, topRecruiters: "McKinsey,BCG,Unilever,P&G,Amazon" } },
  { name: "SP Jain Institute of Management", city: "Mumbai", state: "Maharashtra", type: "Private", fees: 1800000, rating: 4.4, totalRatings: 580, established: 1981, nirf: 10, naac: "A+", description: "SP Jain is Mumbai's most respected business school, known for strong finance and marketing placements in the city's banking and media ecosystem.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/SP_Jain_Institute_Mumbai.jpg/1280px-SP_Jain_Institute_Mumbai.jpg", courses: [{ name: "PGDM", duration: 2, fees: 1800000, seats: 240 }, { name: "Executive PGDM", duration: 1, fees: 2200000, seats: 60 }], placement: { avgPackage: 2100, highestPackage: 70000, placementRate: 100, topRecruiters: "Goldman Sachs,BCG,Amazon,Deloitte,HSBC" } },
  { name: "National Law School of India University", city: "Bengaluru", state: "Karnataka", type: "Government", fees: 320000, rating: 4.7, totalRatings: 420, established: 1987, nirf: 1, naac: "A++", description: "NLSIU is India's finest law school and the template for the National Law University model. Its graduates dominate India's top law firms and the judiciary.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/National_Law_School_of_India_University.jpg/1280px-National_Law_School_of_India_University.jpg", courses: [{ name: "B.A. LLB (Hons)", duration: 5, fees: 320000, seats: 80 }, { name: "LLM", duration: 1, fees: 200000, seats: 40 }], placement: { avgPackage: 1800, highestPackage: 40000, placementRate: 100, topRecruiters: "AZB,Cyril Amarchand,Khaitan,S&R,Trilegal" } },
  { name: "AIIMS New Delhi", city: "New Delhi", state: "Delhi", type: "Government", fees: 12000, rating: 4.9, totalRatings: 1800, established: 1956, nirf: 1, naac: "A++", description: "AIIMS Delhi is not just India's best medical college — it is one of Asia's finest hospitals and research institutions. Entry is near-impossible; prestige is unmatched.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/AIIMS_New_Delhi_main_block.jpg/1280px-AIIMS_New_Delhi_main_block.jpg", courses: [{ name: "MBBS", duration: 5, fees: 12000, seats: 107 }, { name: "B.Sc. Nursing", duration: 4, fees: 12000, seats: 60 }], placement: { avgPackage: 1200, highestPackage: 8000, placementRate: 100, topRecruiters: "AIIMS,PGI,Apollo,Fortis,Max Healthcare" } },
  { name: "Christian Medical College Vellore", city: "Vellore", state: "Tamil Nadu", type: "Private", fees: 140000, rating: 4.7, totalRatings: 980, established: 1900, nirf: 3, naac: "A++", description: "CMC Vellore is India's most respected private medical college. Its century-old legacy of service, research, and clinical training is unmatched in the country.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Christian_Medical_College_Vellore.jpg/1280px-Christian_Medical_College_Vellore.jpg", courses: [{ name: "MBBS", duration: 5, fees: 140000, seats: 100 }, { name: "B.Sc. Nursing", duration: 4, fees: 80000, seats: 60 }], placement: { avgPackage: 1100, highestPackage: 7500, placementRate: 100, topRecruiters: "CMC,Apollo,Fortis,Aga Khan,NHS UK" } },
  { name: "Savitribai Phule Pune University", city: "Pune", state: "Maharashtra", type: "Government", fees: 65000, rating: 3.9, totalRatings: 2800, established: 1949, nirf: 23, naac: "A++", description: "SPPU is one of India's largest universities affiliating 800+ colleges. Its direct programs and proximity to Pune's IT corridor make it highly placement-relevant.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Savitribai_Phule_Pune_University_Main_Building.jpg/1280px-Savitribai_Phule_Pune_University_Main_Building.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 65000, seats: 200 }, { name: "B.Sc. Computer Science", duration: 3, fees: 40000, seats: 150 }], placement: { avgPackage: 580, highestPackage: 6500, placementRate: 70, topRecruiters: "TCS,Infosys,Wipro,Persistent,Cognizant" } },
  { name: "Mumbai University", city: "Mumbai", state: "Maharashtra", type: "Government", fees: 55000, rating: 3.7, totalRatings: 5400, established: 1857, nirf: 29, naac: "A+", description: "One of Asia's oldest universities, Mumbai University's affiliated colleges produce India's largest graduate workforce. Its South Mumbai campus is historically iconic.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/University_of_Mumbai_Fort_Campus.jpg/1280px-University_of_Mumbai_Fort_Campus.jpg", courses: [{ name: "B.E. Computer Engineering", duration: 4, fees: 55000, seats: 300 }, { name: "B.Com", duration: 3, fees: 25000, seats: 500 }], placement: { avgPackage: 480, highestPackage: 5500, placementRate: 68, topRecruiters: "TCS,Infosys,Wipro,HDFC,ICICI" } },
  { name: "IIT Roorkee", city: "Roorkee", state: "Uttarakhand", type: "Government", fees: 225000, rating: 4.6, totalRatings: 1700, established: 1847, nirf: 6, naac: "A++", description: "The oldest technical institution in Asia, IIT Roorkee combines 175+ years of legacy with cutting-edge research. Its civil engineering program is among the world's best.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/IIT_Roorkee_Campus_Aerial.jpg/1280px-IIT_Roorkee_Campus_Aerial.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 225000, seats: 90 }, { name: "B.Tech Civil Engineering", duration: 4, fees: 225000, seats: 100 }], placement: { avgPackage: 1850, highestPackage: 21000, placementRate: 92, topRecruiters: "Google,Microsoft,Amazon,McKinsey,Samsung" } },
  { name: "IIT Guwahati", city: "Guwahati", state: "Assam", type: "Government", fees: 215000, rating: 4.4, totalRatings: 1200, established: 1994, nirf: 7, naac: "A++", description: "IIT Guwahati's stunning campus on the Brahmaputra riverbank is one of India's most beautiful. It is the gateway IIT for North-East India with rapidly rising rankings.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/IIT_Guwahati_from_Brahmaputra.jpg/1280px-IIT_Guwahati_from_Brahmaputra.jpg", courses: [{ name: "B.Tech Computer Science", duration: 4, fees: 215000, seats: 80 }, { name: "B.Tech Electronics", duration: 4, fees: 215000, seats: 70 }], placement: { avgPackage: 1650, highestPackage: 19000, placementRate: 90, topRecruiters: "Amazon,Google,Microsoft,Flipkart,Samsung" } },
  { name: "Indian Statistical Institute", city: "Kolkata", state: "West Bengal", type: "Government", fees: 40000, rating: 4.6, totalRatings: 450, established: 1931, nirf: 8, naac: "A++", description: "ISI Kolkata is a globally recognized institution for statistics, mathematics, and computer science. Its B.Stat and B.Math programs are among the world's most selective.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Indian_Statistical_Institute_Kolkata.jpg/1280px-Indian_Statistical_Institute_Kolkata.jpg", courses: [{ name: "B.Stat", duration: 3, fees: 40000, seats: 30 }, { name: "B.Math", duration: 3, fees: 40000, seats: 20 }], placement: { avgPackage: 1800, highestPackage: 22000, placementRate: 94, topRecruiters: "Google,Amazon,D.E.Shaw,Goldman Sachs,Two Sigma" } },
  { name: "NIFT Delhi", city: "New Delhi", state: "Delhi", type: "Government", fees: 250000, rating: 4.4, totalRatings: 890, established: 1986, nirf: 1, naac: "A++", description: "India's premier fashion institute. NIFT Delhi produces the country's finest fashion designers who go on to lead global luxury brands and create iconic Indian fashion labels.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/NIFT_New_Delhi_Campus.jpg/1280px-NIFT_New_Delhi_Campus.jpg", courses: [{ name: "B.Des Fashion Design", duration: 4, fees: 250000, seats: 50 }, { name: "B.Des Textile Design", duration: 4, fees: 250000, seats: 40 }], placement: { avgPackage: 680, highestPackage: 5000, placementRate: 90, topRecruiters: "Zara,H&M,Fabindia,Manyavar,Raymond" } },
];

async function main() {
  console.log("🌱 Seeding 50 colleges...");

  await prisma.user.upsert({
    where: { email: "test@demo.com" },
    update: {},
    create: { email: "test@demo.com", name: "Demo User", password: "demo1234" },
  });

  for (const col of colleges) {
    const { courses, placement, ...data } = col;
    const id = col.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
    const location = `${col.city}, ${col.state}`;

    try {
      await prisma.college.upsert({
        where: { id },
        update: {},
        create: {
          id, ...data, location,
          courses: { create: courses },
          placements: { create: placement },
        },
      });
      console.log(`✅ ${col.name}`);
    } catch (e) {
      console.error(`❌ ${col.name}:`, e);
    }
  }

  console.log("✅ Done!");
}

main().catch(console.error).finally(() => prisma.$disconnect());